require('./color')
  prototype: true

p = console.log

p "white".tcolor ['white']
p "grey".tcolor ['grey']
p "black".tcolor ['black']
p "blue".tcolor ['blue']
p "cyan".tcolor ['cyan']
p "green".tcolor ['green']
p "magenta".tcolor ['magenta']
p "red".tcolor ['red']
p "yellow".tcolor ['yellow']

p "bold white".tcolor ['white', 'bold']
p "bold grey".tcolor ['grey', 'bold']
p "bold black".tcolor ['black', 'bold']
p "bold blue".tcolor ['blue', 'bold']
p "bold cyan".tcolor ['cyan', 'bold']
p "bold green".tcolor ['green', 'bold']
p "bold magenta".tcolor ['magenta', 'bold']
p "bold red".tcolor ['red', 'bold']
p "bold yellow".tcolor ['yellow', 'bold']

p "underline white".tcolor ['white', 'underline']
p "underline grey".tcolor ['grey', 'underline']
p "underline black".tcolor ['black', 'underline']
p "underline blue".tcolor ['blue', 'underline']
p "underline cyan".tcolor ['cyan', 'underline']
p "underline green".tcolor ['green', 'underline']
p "underline magenta".tcolor ['magenta', 'underline']
p "underline red".tcolor ['red', 'underline']
p "underline yellow".tcolor ['yellow', 'underline']

p "italic white".tcolor ['white', 'italic']
p "italic grey".tcolor ['grey', 'italic']
p "italic black".tcolor ['black', 'italic']
p "italic blue".tcolor ['blue', 'italic']
p "italic cyan".tcolor ['cyan', 'italic']
p "italic green".tcolor ['green', 'italic']
p "italic magenta".tcolor ['magenta', 'italic']
p "italic red".tcolor ['red', 'italic']
p "italic yellow".tcolor ['yellow', 'italic']

p "inverse white".tcolor ['white', 'inverse']
p "inverse grey".tcolor ['grey', 'inverse']
p "inverse black".tcolor ['black', 'inverse']
p "inverse blue".tcolor ['blue', 'inverse']
p "inverse cyan".tcolor ['cyan', 'inverse']
p "inverse green".tcolor ['green', 'inverse']
p "inverse magenta".tcolor ['magenta', 'inverse']
p "inverse red".tcolor ['red', 'inverse']
p "inverse yellow".tcolor ['yellow', 'inverse']
